version: "3"
services:
  
  jobmanager:
    build: ./flink
    expose:
      - "6123"
      - "9249"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=cluster
    volumes:
      - /tmp/flink-docker:/tmp/flink-docker

  taskmanager:
    build: ./flink
    ports:
      - "5005:5005"
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:cluster"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=cluster
    volumes:
      - /tmp/flink-docker:/tmp/flink-docker

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - prometheus
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - jobmanager
      - taskmanager
    command: "--log.level=debug --config.file=/etc/prometheus/prometheus.yml"


  
  