{
 "title": "Flink",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "JOB_ID", "label": "Job ID", "query": "flink_jobmanager_job_uptime" }
  ]
 },
 "panels": [
  {
   "title": "Generated transactions per s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(created_transactions[20s])"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "generator_end_to_end_latency",
     "legendFormat": "{{quantile}}th quantile measured at {{operator_name}} ({{operator_id}})"
    }
   ]
  },
  {
   "title": "Records Out per Second",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond{job_id=\"$JOB_ID\"}",
     "legendFormat": "{{operator_name}}"
    },
    {}
   ]
  },
  {
   "title": "Records In per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsInPerSecond{job_id=\"$JOB_ID\"}",
     "legendFormat": "{{operator_name}}"
    }
   ]
  }
 ]
}